### ISSUE TITLE
Issue with version of event-stream (flatmap-stream) packages in package-lock

### ISSUE THREAD

**Issue by whazap** [kentcdodds/react-github-profile#5]
So i just started with your egghead tutorial on hooks (https://egghead.io/lessons/react-refactor-a-class-component-with-react-hooks-to-a-function). (thanks for doing those!)

When trying to install the dependencies via npm i get the following error:
> npm ERR! notarget No matching version found for flatmap-stream@0.1.2

which is related to npm removing that package https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident

just a heads up for you or anyone running into this issue.
quick solutions:
- install an older version of event-stream (npm i event-stream@3.3.5)
- remove package-lock and try again
- yarn

**Comment by kentcdodds** [comment]
Thank you for bringing this up! I'll fix it 💯

**Comment by kentcdodds** [comment]
Fixed!
