### ISSUE TITLE
404 when using `npm ci`

### ISSUE THREAD

**Issue by adam-beck** [kentcdodds/react-github-profile#6]
I cloned this repo and attempted to install the dependencies using `npm ci`. However, I was getting a 404 because the `"docz": "0.12.9"` package has a dependency that no longer exists. 

### Unnecessary details
I'm a little confused how this dependency works because it is a lerna type project. But, in the `package-lock.json` file of this repo it attempts to pull in `docz-core` which relies on `get-pkg-repo` which relies on `@hbetts/parse-repository-url` which no longer exists. It has been renamed to `@hutson/parse-repository-url` which was fixed by `get-pgk-repo` in [this commit](https://github.com/conventional-changelog/get-pkg-repo/commit/5a9de01bf6d44c52ca8579ccac80c573be463ff5#diff-b9cfc7f2cdf78a7f4b91a753d10865a2)

### Solution
I think just an update to the `package-lock.json` file is necessary. I wanted to create a PR for this but was running into an npm bug where the call stack size was exceeded.

**Comment by kentcdodds** [comment]
Hi @adam-beck!

That's pretty odd. The npm registry is supposed to be immutable so I can't fathom how a package that installed ok before is no longer available on the registry. Doe sit work when using `npm install`? I don't really care to support `npm ci` in this example project.

**Comment by adam-beck** [comment]
I believe it would work but again I have to use yarn because I get the following error when trying to run `npm install`. `yarn install` works just fine.

```
$ npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/adam/a/b/node_modules/.staging/fsevents-aa64f3f9/node_modules/abbrev' -> '/home/adam/a/b/node_modules/.staging/abbrev-165b53bc'

npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/adam/.npm/_logs/2019-01-25T14_48_22_919Z-debug.log
```

However, if you don't care about the `npm ci` command then I think this issue could be closed. I don't know if I fully understand the purpose of the `packge-lock.json` file so maybe this issue was opened prematurely.
